@isTest
public with sharing class FON_ContactFilterClsTest
{
	@isTest
	static void testGetPBcon()
	{
		FON_ContactFilterCls contactFilter = new FON_ContactFilterCls();
		contactFilter.GetPBcon();
	}

	@isTest
	static void testGetBcon()
	{
		FON_ContactFilterCls contactFilter = new FON_ContactFilterCls();
		contactFilter.GetBcon();
	}

	@isTest
	static void testGetSMcon()
	{
		FON_ContactFilterCls contactFilter = new FON_ContactFilterCls();
		contactFilter.GetSMcon();
	}

	@isTest
	static void testGetSMrepcon()
	{
		FON_ContactFilterCls contactFilter = new FON_ContactFilterCls();
		contactFilter.GetSMrepcon();
	}

	@isTest
	static void testGetOppsconalt()
	{
		FON_ContactFilterCls contactFilter = new FON_ContactFilterCls();
		contactFilter.GetOppsconalt();
	}

	@isTest
	static void testGetLPCcon()
	{
		FON_ContactFilterCls contactFilter = new FON_ContactFilterCls();
		contactFilter.GetLPCcon();
	}

	@isTest
	static void testGetLPRcon()
	{
		FON_ContactFilterCls contactFilter = new FON_ContactFilterCls();
		contactFilter.GetLPRcon();
	}

	@isTest
	static void testGetBusComMaincon()
	{
		FON_ContactFilterCls contactFilter = new FON_ContactFilterCls();
		contactFilter.GetBusComMaincon();
	}

	@isTest
	static void testGetBusComAltcon()
	{
		FON_ContactFilterCls contactFilter = new FON_ContactFilterCls();
		contactFilter.GetBusComAltcon();
	}

	@isTest
	static void testGetMainOpscon()
	{
		FON_ContactFilterCls contactFilter = new FON_ContactFilterCls();
		contactFilter.GetMainOpscon();
	}
}